import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <div className="min-h-screen w-full flex flex-col">
            <Header />
            <main className="mx-auto w-full max-w-4xl px-4 sm:px-6 lg:px-8 flex-1">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
