import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="min-h-screen w-full flex flex-col">
          <Header />
          <main className="mx-auto w-full max-w-4xl flex-1 flex flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
}
